# Generated by Django 3.2 on 2021-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210805_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(choices=[(1, 'Patient'), (0, 'Doctor')], default=0),
        ),
    ]
