# Generated by Django 3.2 on 2021-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='10', height_field='10', upload_to='', width_field='10'),
            preserve_default=False,
        ),
    ]
